#!/bin/sh

DOTFILES_LOCATION=$HOME/projects/dotfiles

# Haskell
export PATH=$HOME/.cabal/bin:$PATH

# Rust
export PATH=$HOME/.cargo/bin:$PATH

# Ruby (rbenv)
export PATH=$HOME/.rbenv/bin:$PATH
if command -v rbenv &>/dev/null; then
  eval "$(rbenv init -)"
fi

# Yarn
export PATH=$HOME/.config/yarn/global/node_modules/.bin:$PATH

# my stuff
export PATH=$HOME/bin:$DOTFILES_LOCATION/bin:$PATH
