#!/bin/sh

# D-bus
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval `dbus-launch --sh-syntax --exit-with-session`
fi

# assuming you're using Network Manager
xhost + && nm-applet &
if ssh-add -l | grep "The agent has no identities"; then
  ssh-add .ssh/identity .ssh/id_rsa </dev/null
fi

# scim stuff
export XMODIFIERS="@im=SCIM"
export GTK_IM_MODULE="scim-bridge"
export LANG=en_US.UTF-8
scim -d

xmodmap ~/.Xmodmap

# awesome receives xinit's process id; when it terminates, X will be terminated
exec awesome
