#!/bin/sh

# D-bus
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval `dbus-launch --sh-syntax --exit-with-session`
fi

# assuming you're using Network Manager
xhost + && nm-applet &
# awesome receives xinit's process id; when it terminates, X will be terminated
exec awesome
