#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   All system aliases are stored here.

#--------------------------------------------------
#    OS-specific aliases
#--------------------------------------------------
dir=$(dirname $0)
if [ -f "${dir}/aliases.d/${os}" ]; then
  source ${dir}/aliases.d/${os}
fi

#--------------------------------------------------
#    Bash command aliases
#--------------------------------------------------
alias cl='clear'
alias cp='nocorrect cp'
alias df='df -H'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias psh='~/.zsh.d/functions.d/psh.pl'
alias pscp='psh --scp'
alias psftp='psh --sftp'
alias realpath='~/.zsh.d/functions.d/realpath.py'
alias rf='rm -rf'
alias rsrc='source ~/.zshrc'

#--------------------------------------------------
#    Bash FBMVC aliases
#--------------------------------------------------
alias fbmvc='./fbmvc'
alias gut='git'
alias ifb='./fbmvc ifb'

#--------------------------------------------------
#   Git aliases
#--------------------------------------------------
alias gd='git diff'
alias gl='git lg'
alias gs='git status'

#--------------------------------------------------
#   SSH aliases
#--------------------------------------------------
alias bap='psh --ssh $bap'
alias brep='psh --ssh $brep'
alias bstar='psh --ssh $bstar'
alias harmonic='psh --ssh $harmonic'
alias wk='psh --ssh $wk'

#--------------------------------------------------
#    SSH aliases (Fusionbox)
#--------------------------------------------------
alias buggy='psh --ssh $buggy'
alias cims='psh --ssh $cims'
alias dg='psh --ssh $dg'
alias elements='psh --ssh $elements'
alias fbcom='psh --ssh $fbcom'
alias fbt='psh --ssh $fbt'
alias ft='psh --ssh $ft'
alias luminate='psh --ssh $luminate'
alias mvoy='psh --ssh $mvoy'
alias nord='psh --ssh $nordsted'