#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   This file sources shell functions on a general level
#   and on OS-specific level

#--------------------------------------------------
#    Generic shell functions
#--------------------------------------------------
dir=$(dirname $0)
for function in ${dir}/functions.d/*.sh; do
  source $function
done

#--------------------------------------------------
#    OS-specific shell functions
#--------------------------------------------------
if [ -d "${dir}/functions.d/${os}" ]; then
  for function in ${dir}/functions.d/${os}/*.sh; do
    source $function
  done
fi