#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   This file sources functions on a general level and
#   an OS-specific level

#--------------------------------------------------
#    OS-specific parameters
#--------------------------------------------------
# Go through zsh.d one file at a time and source everything.
dir=$(dirname $0)
for function in ${dir}/functions.d/*.sh; do
  source $function
done

if [ -d "${dir}/functions.d/${os}" ]; then
  for function in ${dir}/functions.d/${os}/*.sh; do
    source $function
  done
fi