#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   Keybindings (generic and OS-specific) are stored here.
autoload -U compinit
compinit

#--------------------------------------------------
#    OS-specific binds
#--------------------------------------------------
if [ -f "${dotfile_dir}/dotfiles.d/binds.d/${os}" ]; then
  source ${dotfile_dir}/dotfiles.d/binds.d/${os}
fi
