#!/usr/bin/env bash
#-------------------------------------------------------
#   environment - Overview
#-------------------------------------------------------
#   This file exports environment variables.  It figures
#   out what OS we're on and loads vars specific to that
#   OS, as well.

#--------------------------------------------------
#    OS-specific parameters
#--------------------------------------------------
if [ -f "${dotfile_dir}/dotfiles.d/environment.d/${os}" ]; then
  source ${dotfile_dir}/dotfiles.d/environment.d/${os}
fi

#--------------------------------------------------
#    Exported parameters
#--------------------------------------------------
export DISPLAY=:0
export TZ="America/Denver"
export PAGER='less'

#--------------------------------------------------
#    Language parameters
#--------------------------------------------------
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LC_CTYPE=C