#!/usr/bin/env zsh
#-------------------------------------------------------
#   git_prompt - Overview
#-------------------------------------------------------
#   Thanks 
#   http://sebastiancelis.com/2009/nov/16/zsh-prompt-git-users/

# Enable auto-execution of functions.
typeset -ga precmd_functions
typeset -ga chpwd_functions
 
# Append git functions needed for prompt.
precmd_functions+='pre_update_git_vars'
chpwd_functions+='update_current_git_vars'
 
update_current_git_vars() {
  unset __CURRENT_GIT_BRANCH
  unset __CURRENT_GIT_BRANCH_STATUS

  local st="$(git status 2>/dev/null)"
  if [[ -n "$st" ]]; then
    local -a arr
    arr=(${(f)st})

    if [[ $arr[1] =~ 'Not currently on any branch.' ]]; then
      __CURRENT_GIT_BRANCH='no-branch'
    else
      __CURRENT_GIT_BRANCH="${arr[1][(w)4]}";
    fi

    if [[ ! $st =~ 'nothing to commit' ]]; then
      __CURRENT_GIT_BRANCH_STATUS='*'
    fi
  fi
}

prompt_git_info() {
  if [ -n "$__CURRENT_GIT_BRANCH" ]; then
    printf "%s" "(%{$PR_LIGHT_YELLOW%}$__CURRENT_GIT_BRANCH%{$PR_LIGHT_RED%}$__CURRENT_GIT_BRANCH_STATUS%{$PR_NO_COLOR%})"
  fi
}

pre_update_git_vars() {
  if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
    update_current_git_vars
  fi
}

update_current_git_vars
