#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   This file sets a multitude of zsh options (in fact,
#   nearly all of them are listed here because they're
#   so useful).

# If dircolors exist, let's utilize them
if test -x dircolors; then
    eval "`dircolors`"
    export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
    export ZLS_COLORS=$LS_COLORS
fi

autoload -U is-at-least

#[ a ]########################################################################################
setopt aliases              # Expand aliases.
setopt all_export           # All parameters subsequently defined are automatically 
														# exported.
setopt always_to_end        # The cursor is moved to the end of the word if either
														# a single match is inserted or menu completion is 
														# performed.
setopt append_history       # zsh sessions will append their history list to the 
														# history file, rather than overwrite it.
setopt auto_cd              # Do cd path if only 'path' is given as command.
setopt auto_continue        # Send SIGCONT to disowned jobs.
setopt auto_list            # Automatically list choices on an ambiguous completion.
setopt auto_menu            # Show menu for completion.
setopt no_autoname_dirs     # After foo=/absolute/path, ~foo may expand to
                            # /absolute/path, but `%~' in prompt won't give
                            # `~foo' until `~foo' has been used (RTFM closely).
setopt auto_param_keys      # Remove trailing spaces after completion (if needed).
setopt auto_param_slash     # Auto add slash for directories.
setopt auto_pushd           # Make cd push the old dir onto the dir stack.
setopt auto_remove_slash    # Remove slash on dirs if word separator added.
setopt auto_resume          # Treat single word simple commands without redirection 
														# as candidates for resumption of an existing job.

#[ b ]########################################################################################
setopt bad_pattern          # Error if a pattern for filename generation is badly 
														# formed.
setopt bang_hist            # Perform textual history expansion, csh-style,
														# treating the character `!' specially.
setopt bare_glob_qual       # In a glob pattern, treat a trailing set of parentheses
														# as a qualifier list, if it contains no `|', `(' or 
														# (if special) `~' characters.
setopt no_bash_auto_list    # Auto_list is sufficient (I want it on first tab).
setopt no_bg_nice           # Don't run all background jobs at a lower priority.
setopt brace_ccl            # Expand expressions in braces which would not otherwise
														# undergo brace expansion to a lexically ordered list of
														# all the characters.
setopt no_bsd_echo          # BSD-compatible echo not needed.

#[ c ]########################################################################################
setopt case_glob            # Make globbing (filename generation) sensitive to case.
setopt c_bases              # Output hexadecimal numbers in the standard C format, 
														# for example `0xFF' instead of the usual `16#FF'.
setopt no_cdable_vars       # Don't automagically add ~ to paths w/o a starting /.
setopt no_chase_dots        # foo/bar/.. is foo/ even if bar is a symlink.
setopt chase_links          # cd to a symlink = cd to the true dir.
setopt check_jobs           # Report the status of background and suspended jobs 
														# before exiting a shell with job control.
setopt clobber              # Allows `>' redirection to truncate existing files, 
														# and `>>' to create files.
setopt complete_aliases     # Prevents aliases on the command line from being 
														# internally substituted before completion is attempted
setopt complete_in_word     # Start completion from current cursor location.
setopt no_correct           # Don't try to correct the spelling of commands.
setopt no_correct_all       # Don't try to correct the spelling of all arguments in a line.
setopt no_csh_junkiehistory # Don't want this.
setopt no_csh_junkie_loops  # Stick with `do list; done'.
setopt no_csh_junkie_quotes # Don't rewire quote rules to match csh.
setopt no_csh_nullcmd       # We want to keep my (READ)?NULLCMD settings.
setopt no_csh_null_glob     # Don't silently erase unmatched globs.

#[ d-g ]######################################################################################
setopt no_dvorak            # Don't use the Dvorak keyboard layout.
setopt no_emacs             # Use bindkeys rather than this deprecated feature.
setopt equals               # Perform = filename expansion.
setopt no_err_exit          # Don't want to see exit status (even if non-zero).
setopt no_err_return        # Don't immediately return from the enclosed function
														# if a command has a non-zero exit status).
setopt exec                 # We actually want to execute commands (and not just
														# check them for correctness).
setopt extended_glob        # Treat the `#', `~' and `^' characters as part of 
                            # patterns for filename generation, etc.
setopt no_extended_history  # Regular history (don't save beginning timestamp).
setopt no_flow_control      # Ignore/Disable ^S/^Q.
setopt function_argzero     # When executing a shell function or sourcing a script,
                            # set $0 temporarily to the name of the function/script.
setopt glob                 # Perform filename generation (globbing).
setopt no_global_export     # Local vars are not made global.
setopt global_rcs           # The startup files /etc/zprofile, /etc/zshrc, /etc/zlogin 
                            # and /etc/zlogout will not be run.
setopt no_glob_assign       # No globbing on foo=* - use foo=(*).
setopt no_glob_complete     # Don't generate glob matches and cycle through them.
setopt no_glob_dots         # Do not require a leading `.' in a filename to be matched explicitly.
setopt no_glob_subst        # No recursive expansion.

#[ h-j ]######################################################################################
setopt hash_cmds            # Note the location of each command the first time it is executed
                            # (don't have to do a path search each time - basically command
                            # caching).
setopt hash_dirs            # Hash directories, too.
setopt hash_list_all        # Whenever a command completion is attempted, make sure the entire 
                            # command path is hashed first. This makes the first completion slower.
setopt hist_allow_clobber   # Add `|' to output redirections in the history.
setopt no_hist_beep         # Beep when an attempt is made to access a history entry which isn't there.
setopt hist_find_no_dups    # Do not display duplicates of a line previously found.
setopt hist_ignore_all_dups # Older command is removed from the list.
setopt no_hist_ignore_space # Hold onto commands in the history that start with spaces.
setopt hist_no_functions    # Remove function definitions from the history list.
setopt hist_no_store        # Remove the history (fc -l) command from the history list when invoked.
setopt hist_reduce_blanks   # Remove superfluous blanks.
setopt hist_save_no_dups    # When writing out the history file, older commands that duplicate 
                            # newer ones are omitted.
setopt hist_verify          # Whenever the user enters a line with history expansion, don't 
                            # execute the line directly; instead, perform history expansion and
                            # reload the line into the editing buffer.
setopt no_hup               # Don't send the HUP signal to running jobs when the shell exits.
setopt no_ignore_braces     # Perform brace expansion.
setopt no_ignore_eof        # Don't ignore ^D when trying to quit the shell.
setopt no_inc_appendhistory # Don't append incrementally to the history.
setopt interactive_comments # Allow comments in interactive shells.

#[ k-o ]######################################################################################
setopt no_ksh_arrays        # Don't emulate ksh arrays.
setopt no_ksh_autoload      # Don't emulate ksh autoloading.
setopt no_ksh_glob          # Ignore `@', `*', `+', `?' and `!' before ().
setopt ksh_option_print     # All options are shown, marked `on' if they are in the non-default 
                            # state, `off' otherwise.
setopt no_ksh_typeset       # Use zsh typeset.
setopt list_ambiguous       # Unambiguous prefix completion is done silently.
setopt no_list_beep         # Don't beep for ambiguous completion.
setopt list_packed          # Try to make the completion list smaller (occupying less lines) by
                            # printing the matches in columns with different widths.
setopt no_list_rows_first   # Sort matches by column (vertically) rather than by row (horizontally).
setopt list_types           # When listing files that are possible completions, show the type of 
                            # each file with a trailing identifying mark.
setopt long_list_jobs       # List jobs in the long format by default.
setopt magic_equal_subst    # All unquoted arguments of the form `anything=expression' appearing 
                            # after the command name have filename expansion (that is, where 
                            # expression has a leading `~' or `=') performed on expression as if 
                            # it were a parameter assignment.
setopt no_mail_warning      # Don't print a warning message if a mail file has been accessed 
                            # since the shell last checked.
setopt mark_dirs            # Add / onto the end of dirs in filename completion.
setopt no_menu_complete     # Don't show menu on ambiguous completion.
setopt monitor              # Allow job control.
setopt multios              # Perform implicit tees or cats when multiple redirections are attempted.
setopt nomatch              # Print error on non-matched patterns.
setopt notify               # Report the status of background jobs immediately, rather than waiting 
                            # until just before printing a prompt.
setopt no_null_glob         # Don't delete non-matched globs.
setopt numeric_glob_sort    # Sort in numeric order rather than lexicographically.
setopt no_octal_zeroes      # 010 = 9 sucks (?).
setopt no_overstrike        # Don't start line editor in overstrike mode.

#[ p-r ]######################################################################################
setopt path_dirs            # Perform a path search even on command names with slashes in them.
setopt no_posix_builtins    # Don't allow `command' builtin to execute shell builtin commands.
setopt print_eight_bit      # Print eight bit characters literally in completion lists, etc.
setopt no_prompt_bang       # Don't perform history expansion when ! is given.
setopt no_prompt_cr         # Don't print a carriage return just before printing a prompt in
                            # the line editor.
setopt prompt_percent       # Expand % in prompt (treated specially).
setopt prompt_subst         # Allow parameter, command, and arithmetic expansion.
setopt pushd_ignore_dups    # Don't push multiple copies of the same directory onto the directory
                            # stack.
setopt pushd_silent         # Do not print the directory stack after pushd or popd.
setopt pushd_to_home        # Have pushd with no arguments act like `pushd $HOME'.
setopt rc_expand_param      # Array expansions of the form `foo${xx}bar', where the parameter xx 
                            # is set to (a b c), are substituted with `fooabar foobbar foocbar' 
                            # instead of the default `fooa b cbar'.
setopt rc_quotes            # Allow the character sequence `"' to signify a single quote within
                            # singly quoted strings.
setopt rcs                  # Source all /etc rc files.
setopt no_rec_exact         # Don't recognize exact match in completion, even if ambiguous.
setopt rm_star_silent       # Do not query the user before executing `rm *' or `rm path/*'.
setopt no_rm_star_wait      # Dont't idle 10 seconds during `rm *' or `rm path/*'.

#[ s-z ]######################################################################################
setopt no_share_history     # Traditional bash history.
setopt no_sh_file_expansion # Don't expand filenames before paramters, commands, or arithmetic.
setopt no_sh_glob           # Allow globbing with [(|)<].
setopt no_sh_nullcmd        # Use the values of NULLCMD and READNULLCMD when doing redirections.
setopt sh_option_letters    # Interprete single option letters like ksh does.
setopt short_loops          # Allow the short forms of for, repeat, select, if, and function constructs.
setopt no_sh_word_split     # `s="a b"; a=($s)' => array of length 1, not 2.
setopt no_single_line_zle   # Use multiline editor.
setopt no_sun_keyboard_hack # I don't use a Sun keyboard.
setopt transient_rprompt    # Remove any right prompt from display when accepting a command line.
                            # This may be useful with terminals with other cut/paste methods.
setopt vi                   # Use Vi-style bindkeys.
setopt no_xtrace            # Don't print commands and their arguments as they are executed.
setopt zle                  # Use zsh line editor.

is-at-least 4.3.0 && {
	unsetopt hist_save_by_copy
}

HISTFILE=~/.histfile
HISTSIZE=10000              # size of history
LISTMAX=1000                # never ask
NULLCMD='cat'               # use cat for > null commands
REPORTTIME=2                # report time if execution exceeds amount of seconds
SAVEHIST=10000              # maximum of history events to be save
LOGCHECK=60
watch=(notme)               # watch login/logout
WORDCHARS="*?_-.[]~/&;!#$%^(){}<>"
                            # part of word in line editor
