#!/usr/bin/env bash

#--------------------------------------------------
#   Bash command aliases
#--------------------------------------------------
alias rf='rm -rf'
alias rsrc='source ${dotfile_dir}/zshrc'
alias topcmds='cut -d\  -f 1 ~/.histfile | sort | uniq -c | sort -rn | head -n 10 | sed "s/.*/    &/g"'

#!/usr/bin/env bash
#--------------------------------------------------
#    Linux-specific aliases
#--------------------------------------------------

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias egrep='egrep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias grep='grep --color=auto'
  alias ls='ls --color=auto -h -I "*.pyc"'
  alias ll='ls -al'
fi

alias ack='ack-grep'
alias configtest='sudo /usr/sbin/apache2ctl configtest'

alias vi='vim'

alias gpfs='gpp && fab stage'

alias ma='./manage.py'
