#!/usr/bin/env bash
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   This file sources functions in the autoload folder
#   regardless of OS.  Right now, only autoloading of
#   shell functions is accepted.

#--------------------------------------------------
#    Generic shell functions to autoload
#--------------------------------------------------
for function in ${dotfile_dir}/autoload/*; do
  if [[ "$function" =~ .+\.sh$ ]]; then
    source $function
  else 
    if [ -d $function ]; then
      continue
    else
      echo "Not autoloading ${function} (only .sh allowed)"
    fi
  fi
done


#--------------------------------------------------
#    Git functions to autoload
#--------------------------------------------------
for function in ${dotfile_dir}/git/functions/*; do
  if [[ "$function" =~ .+\.sh$ ]]; then
    source $function
  else 
    if [ -d $function ]; then
      continue
    else
      echo "Not autoloading ${function} (only .sh allowed)"
    fi
  fi
done

